(function(b){var k={init:function(a){return this.each(function(){var c=b(this),e=c.data("monthpicker"),h=a&&a.year?a.year:(new Date).getFullYear(),f=b.extend({pattern:"mm/yyyy",selectedMonth:null,selectedMonthName:"",selectedYear:h,startYear:h-10,finalYear:h+10,monthNames:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),id:"monthpicker_"+(Math.random()*Math.random()).toString().replace(".",""),openOnFocus:!0,disabledMonths:[]},a);f.dateSeparator=f.pattern.replace(/(mmm|mm|m|yyyy|yy|y)/ig,
"");if(!e){b(this).data("monthpicker",{target:c,settings:f});if(!0===f.openOnFocus)c.on("focus",function(){c.monthpicker("show")});c.monthpicker("parseInputValue",f);c.monthpicker("mountWidget",f);c.on("monthpicker-click-month",function(a,b,e){c.monthpicker("setValue",f);c.monthpicker("hide")});c.addClass("mtz-monthpicker-widgetcontainer");b(document).unbind("mousedown.mtzmonthpicker").on("mousedown.mtzmonthpicker",function(a){(!a.target.className||0>a.target.className.toString().indexOf("mtz-monthpicker"))&&
b(this).monthpicker("hideAll")})}})},show:function(){b(this).monthpicker("hideAll");var a=b("#"+this.data("monthpicker").settings.id);a.css("top",this.offset().top+this.outerHeight());b(window).width()>a.width()+this.offset().left?a.css("left",this.offset().left):a.css("left",this.offset().left-a.width());a.show();a.find("select").focus();this.trigger("monthpicker-show")},hide:function(){var a=b("#"+this.data("monthpicker").settings.id);a.is(":visible")&&(a.hide(),this.trigger("monthpicker-hide"))},
hideAll:function(){b(".mtz-monthpicker-widgetcontainer").each(function(){"undefined"!=typeof b(this).data("monthpicker")&&b(this).monthpicker("hide")})},setValue:function(a){var b=a.selectedMonth,e=a.selectedYear;0<=a.pattern.indexOf("mmm")?b=a.selectedMonthName:0<=a.pattern.indexOf("mm")&&10>a.selectedMonth&&(b="0"+a.selectedMonth);0>a.pattern.indexOf("yyyy")&&(e=e.toString().substr(2,2));a.pattern.indexOf("y")>a.pattern.indexOf(a.dateSeparator)?this.val(b+a.dateSeparator+e):this.val(e+a.dateSeparator+
b);this.change()},disableMonths:function(a){var c=this.data("monthpicker").settings,e=b("#"+c.id);c.disabledMonths=a;e.find(".mtz-monthpicker-month").each(function(){var c=parseInt(b(this).data("month"));0<=b.inArray(c,a)?b(this).addClass("ui-state-disabled"):b(this).removeClass("ui-state-disabled")})},mountWidget:function(a){var c=this,e=b('<div id="'+a.id+'" class="ui-datepicker ui-widget ui-widget-content ui-helper-clearfix ui-corner-all" />'),h=b('<div class="ui-datepicker-header ui-widget-header ui-helper-clearfix ui-corner-all mtz-monthpicker" />'),
f=b('<select class="mtz-monthpicker mtz-monthpicker-year" />'),k=b('<table class="mtz-monthpicker" />'),l=b('<tbody class="mtz-monthpicker" />'),m=b('<tr class="mtz-monthpicker" />'),g="",g=null,d=b(this).data("selected-year"),g=b(this).data("start-year"),n=b(this).data("final-year");d&&(a.selectedYear=d);g&&(a.startYear=g);n&&(a.finalYear=n);e.css({position:"absolute",zIndex:999999,whiteSpace:"nowrap",width:"250px",overflow:"hidden",textAlign:"center",display:"none",top:c.offset().top+c.outerHeight(),
left:c.offset().left});f.on("change",function(){var d=b(this).parent().parent().find("td[data-month]");d.removeClass("ui-state-active");b(this).val()==a.selectedYear&&d.filter("td[data-month="+a.selectedMonth+"]").addClass("ui-state-active");c.trigger("monthpicker-change-year",b(this).val())});for(d=a.startYear;d<=a.finalYear;d++)g=b('<option class="mtz-monthpicker" />').attr("value",d).append(d),a.selectedYear==d&&g.attr("selected","selected"),f.append(g);h.append(f).appendTo(e);for(d=1;12>=d;d++)g=
b('<td class="ui-state-default mtz-monthpicker mtz-monthpicker-month" style="padding:5px;cursor:default;" />').attr("data-month",d),a.selectedMonth==d&&g.addClass("ui-state-active"),g.append(a.monthNames[d-1]),m.append(g).appendTo(l),0===d%3&&(m=b('<tr class="mtz-monthpicker" />'));l.find(".mtz-monthpicker-month").on("click",function(){var d=parseInt(b(this).data("month"));0>b.inArray(d,a.disabledMonths)&&(a.selectedYear=b(this).closest(".ui-datepicker").find(".mtz-monthpicker-year").first().val(),
a.selectedMonth=b(this).data("month"),a.selectedMonthName=b(this).text(),c.trigger("monthpicker-click-month",b(this).data("month")),b(this).closest("table").find(".ui-state-active").removeClass("ui-state-active"),b(this).addClass("ui-state-active"))});k.append(l).appendTo(e);e.appendTo("body")},destroy:function(){return this.each(function(){b(this).removeClass("mtz-monthpicker-widgetcontainer").unbind("focus").removeData("monthpicker")})},getDate:function(){var a=this.data("monthpicker").settings;
return a.selectedMonth&&a.selectedYear?new Date(a.selectedYear,a.selectedMonth-1):null},parseInputValue:function(a){if(this.val()&&a.dateSeparator){var b=this.val().toString().split(a.dateSeparator);0===a.pattern.indexOf("m")?(a.selectedMonth=b[0],a.selectedYear=b[1]):(a.selectedMonth=b[1],a.selectedYear=b[0])}}};b.fn.monthpicker=function(a){if(k[a])return k[a].apply(this,Array.prototype.slice.call(arguments,1));if("object"!==typeof a&&a)b.error("Method "+a+" does not exist on jQuery.mtz.monthpicker");
else return k.init.apply(this,arguments)}})(jQuery);